package cn.aethli.gttss.domain;

import java.io.Serializable;
import java.util.Date;

public class Batch implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.batchId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.batchName
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String batchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column batch.batchDate
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private Date batchDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.batchId
     *
     * @return the value of batch.batchId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.batchId
     *
     * @param batchId the value for batch.batchId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.batchName
     *
     * @return the value of batch.batchName
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getBatchName() {
        return batchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.batchName
     *
     * @param batchName the value for batch.batchName
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setBatchName(String batchName) {
        this.batchName = batchName == null ? null : batchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column batch.batchDate
     *
     * @return the value of batch.batchDate
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public Date getBatchDate() {
        return batchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column batch.batchDate
     *
     * @param batchDate the value for batch.batchDate
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setBatchDate(Date batchDate) {
        this.batchDate = batchDate;
    }
}