package cn.aethli.gttss.domain;

import java.io.Serializable;
import java.util.Date;

public class DefenseApply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defenseapply.id
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defenseapply.createDt
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defenseapply.createBy
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defenseapply.teacherVerify
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    private String teacherVerify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defenseapply.adminVerify
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    private String adminVerify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defenseapply.reason
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table defenseapply
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defenseapply.id
     *
     * @return the value of defenseapply.id
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defenseapply.id
     *
     * @param id the value for defenseapply.id
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defenseapply.createDt
     *
     * @return the value of defenseapply.createDt
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defenseapply.createDt
     *
     * @param createDt the value for defenseapply.createDt
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defenseapply.createBy
     *
     * @return the value of defenseapply.createBy
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defenseapply.createBy
     *
     * @param createBy the value for defenseapply.createBy
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defenseapply.teacherVerify
     *
     * @return the value of defenseapply.teacherVerify
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public String getTeacherVerify() {
        return teacherVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defenseapply.teacherVerify
     *
     * @param teacherVerify the value for defenseapply.teacherVerify
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public void setTeacherVerify(String teacherVerify) {
        this.teacherVerify = teacherVerify == null ? null : teacherVerify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defenseapply.adminVerify
     *
     * @return the value of defenseapply.adminVerify
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public String getAdminVerify() {
        return adminVerify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defenseapply.adminVerify
     *
     * @param adminVerify the value for defenseapply.adminVerify
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public void setAdminVerify(String adminVerify) {
        this.adminVerify = adminVerify == null ? null : adminVerify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defenseapply.reason
     *
     * @return the value of defenseapply.reason
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defenseapply.reason
     *
     * @param reason the value for defenseapply.reason
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }
}