package cn.aethli.gttss.domain;

import java.io.Serializable;
import java.util.Date;

public class DefenseDraft implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.id
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.studentId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.teacherId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.verifyId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    private String verifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.adminVerifyId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    private String adminVerifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.fileName
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.saveFileName
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    private String saveFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.uploadDate
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    private Date uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table defensedraft
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.id
     *
     * @return the value of defensedraft.id
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.id
     *
     * @param id the value for defensedraft.id
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.studentId
     *
     * @return the value of defensedraft.studentId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.studentId
     *
     * @param studentId the value for defensedraft.studentId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.teacherId
     *
     * @return the value of defensedraft.teacherId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.teacherId
     *
     * @param teacherId the value for defensedraft.teacherId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.verifyId
     *
     * @return the value of defensedraft.verifyId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public String getVerifyId() {
        return verifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.verifyId
     *
     * @param verifyId the value for defensedraft.verifyId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public void setVerifyId(String verifyId) {
        this.verifyId = verifyId == null ? null : verifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.adminVerifyId
     *
     * @return the value of defensedraft.adminVerifyId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public String getAdminVerifyId() {
        return adminVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.adminVerifyId
     *
     * @param adminVerifyId the value for defensedraft.adminVerifyId
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public void setAdminVerifyId(String adminVerifyId) {
        this.adminVerifyId = adminVerifyId == null ? null : adminVerifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.fileName
     *
     * @return the value of defensedraft.fileName
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.fileName
     *
     * @param fileName the value for defensedraft.fileName
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.saveFileName
     *
     * @return the value of defensedraft.saveFileName
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public String getSaveFileName() {
        return saveFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.saveFileName
     *
     * @param saveFileName the value for defensedraft.saveFileName
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public void setSaveFileName(String saveFileName) {
        this.saveFileName = saveFileName == null ? null : saveFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.uploadDate
     *
     * @return the value of defensedraft.uploadDate
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.uploadDate
     *
     * @param uploadDate the value for defensedraft.uploadDate
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }
}