package cn.aethli.gttss.domain;

import java.io.Serializable;

public class DefenseDraft implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.id
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.teacherVerifyId
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    private String teacherVerifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.adminVerifyId
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    private String adminVerifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.fileId
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column defensedraft.status
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table defensedraft
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.id
     *
     * @return the value of defensedraft.id
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.id
     *
     * @param id the value for defensedraft.id
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.teacherVerifyId
     *
     * @return the value of defensedraft.teacherVerifyId
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public String getTeacherVerifyId() {
        return teacherVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.teacherVerifyId
     *
     * @param teacherVerifyId the value for defensedraft.teacherVerifyId
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public void setTeacherVerifyId(String teacherVerifyId) {
        this.teacherVerifyId = teacherVerifyId == null ? null : teacherVerifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.adminVerifyId
     *
     * @return the value of defensedraft.adminVerifyId
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public String getAdminVerifyId() {
        return adminVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.adminVerifyId
     *
     * @param adminVerifyId the value for defensedraft.adminVerifyId
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public void setAdminVerifyId(String adminVerifyId) {
        this.adminVerifyId = adminVerifyId == null ? null : adminVerifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.fileId
     *
     * @return the value of defensedraft.fileId
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.fileId
     *
     * @param fileId the value for defensedraft.fileId
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column defensedraft.status
     *
     * @return the value of defensedraft.status
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column defensedraft.status
     *
     * @param status the value for defensedraft.status
     *
     * @mbg.generated Fri May 03 02:26:45 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}