package cn.aethli.gttss.domain;

import java.io.Serializable;

public class Faculty implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.id
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column faculty.name
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table faculty
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.id
     *
     * @return the value of faculty.id
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.id
     *
     * @param id the value for faculty.id
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column faculty.name
     *
     * @return the value of faculty.name
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column faculty.name
     *
     * @param name the value for faculty.name
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}