package cn.aethli.gttss.domain;

import java.io.Serializable;
import java.util.Date;

public class MediumTermRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediumtermrecord.id
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediumtermrecord.status
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediumtermrecord.comment
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    private Integer comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediumtermrecord.createBy
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediumtermrecord.createDt
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediumtermrecord.teacherVerifyId
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    private String teacherVerifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediumtermrecord.adminVerifyId
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    private String adminVerifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mediumtermrecord.summary
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mediumtermrecord
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediumtermrecord.id
     *
     * @return the value of mediumtermrecord.id
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediumtermrecord.id
     *
     * @param id the value for mediumtermrecord.id
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediumtermrecord.status
     *
     * @return the value of mediumtermrecord.status
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediumtermrecord.status
     *
     * @param status the value for mediumtermrecord.status
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediumtermrecord.comment
     *
     * @return the value of mediumtermrecord.comment
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public Integer getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediumtermrecord.comment
     *
     * @param comment the value for mediumtermrecord.comment
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public void setComment(Integer comment) {
        this.comment = comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediumtermrecord.createBy
     *
     * @return the value of mediumtermrecord.createBy
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediumtermrecord.createBy
     *
     * @param createBy the value for mediumtermrecord.createBy
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediumtermrecord.createDt
     *
     * @return the value of mediumtermrecord.createDt
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediumtermrecord.createDt
     *
     * @param createDt the value for mediumtermrecord.createDt
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediumtermrecord.teacherVerifyId
     *
     * @return the value of mediumtermrecord.teacherVerifyId
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public String getTeacherVerifyId() {
        return teacherVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediumtermrecord.teacherVerifyId
     *
     * @param teacherVerifyId the value for mediumtermrecord.teacherVerifyId
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public void setTeacherVerifyId(String teacherVerifyId) {
        this.teacherVerifyId = teacherVerifyId == null ? null : teacherVerifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediumtermrecord.adminVerifyId
     *
     * @return the value of mediumtermrecord.adminVerifyId
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public String getAdminVerifyId() {
        return adminVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediumtermrecord.adminVerifyId
     *
     * @param adminVerifyId the value for mediumtermrecord.adminVerifyId
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public void setAdminVerifyId(String adminVerifyId) {
        this.adminVerifyId = adminVerifyId == null ? null : adminVerifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mediumtermrecord.summary
     *
     * @return the value of mediumtermrecord.summary
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mediumtermrecord.summary
     *
     * @param summary the value for mediumtermrecord.summary
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }
}