package cn.aethli.gttss.domain;

import java.io.Serializable;

public class OpeningReportWithBLOBs extends OpeningReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.statusAndTrends
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String statusAndTrends;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.mainDestination
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String mainDestination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.ideasAndSolutions
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String ideasAndSolutions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.plan
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String plan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table openingreport
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.statusAndTrends
     *
     * @return the value of openingreport.statusAndTrends
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getStatusAndTrends() {
        return statusAndTrends;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.statusAndTrends
     *
     * @param statusAndTrends the value for openingreport.statusAndTrends
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setStatusAndTrends(String statusAndTrends) {
        this.statusAndTrends = statusAndTrends == null ? null : statusAndTrends.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.mainDestination
     *
     * @return the value of openingreport.mainDestination
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getMainDestination() {
        return mainDestination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.mainDestination
     *
     * @param mainDestination the value for openingreport.mainDestination
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setMainDestination(String mainDestination) {
        this.mainDestination = mainDestination == null ? null : mainDestination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.ideasAndSolutions
     *
     * @return the value of openingreport.ideasAndSolutions
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getIdeasAndSolutions() {
        return ideasAndSolutions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.ideasAndSolutions
     *
     * @param ideasAndSolutions the value for openingreport.ideasAndSolutions
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setIdeasAndSolutions(String ideasAndSolutions) {
        this.ideasAndSolutions = ideasAndSolutions == null ? null : ideasAndSolutions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.plan
     *
     * @return the value of openingreport.plan
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getPlan() {
        return plan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.plan
     *
     * @param plan the value for openingreport.plan
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setPlan(String plan) {
        this.plan = plan == null ? null : plan.trim();
    }
}