package cn.aethli.gttss.domain;

import java.io.Serializable;
import java.util.Date;

public class OpeningReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.topicId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.studentId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.teacherId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.teacherVerifyId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String teacherVerifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.defenseVerifyId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String defenseVerifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.createDt
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column openingreport.createBy
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table openingreport
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.topicId
     *
     * @return the value of openingreport.topicId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.topicId
     *
     * @param topicId the value for openingreport.topicId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setTopicId(String topicId) {
        this.topicId = topicId == null ? null : topicId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.studentId
     *
     * @return the value of openingreport.studentId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.studentId
     *
     * @param studentId the value for openingreport.studentId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.teacherId
     *
     * @return the value of openingreport.teacherId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.teacherId
     *
     * @param teacherId the value for openingreport.teacherId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.teacherVerifyId
     *
     * @return the value of openingreport.teacherVerifyId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getTeacherVerifyId() {
        return teacherVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.teacherVerifyId
     *
     * @param teacherVerifyId the value for openingreport.teacherVerifyId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setTeacherVerifyId(String teacherVerifyId) {
        this.teacherVerifyId = teacherVerifyId == null ? null : teacherVerifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.defenseVerifyId
     *
     * @return the value of openingreport.defenseVerifyId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getDefenseVerifyId() {
        return defenseVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.defenseVerifyId
     *
     * @param defenseVerifyId the value for openingreport.defenseVerifyId
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setDefenseVerifyId(String defenseVerifyId) {
        this.defenseVerifyId = defenseVerifyId == null ? null : defenseVerifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.createDt
     *
     * @return the value of openingreport.createDt
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.createDt
     *
     * @param createDt the value for openingreport.createDt
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column openingreport.createBy
     *
     * @return the value of openingreport.createBy
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column openingreport.createBy
     *
     * @param createBy the value for openingreport.createBy
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }
}