package cn.aethli.gttss.domain;

import java.io.Serializable;

public class ResultSubmit implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultsubmit.id
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultsubmit.teacherVerifyId
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    private String teacherVerifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultsubmit.adminVerifyId
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    private String adminVerifyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultsubmit.fileId
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    private String fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resultsubmit.status
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resultsubmit
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultsubmit.id
     *
     * @return the value of resultsubmit.id
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultsubmit.id
     *
     * @param id the value for resultsubmit.id
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultsubmit.teacherVerifyId
     *
     * @return the value of resultsubmit.teacherVerifyId
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public String getTeacherVerifyId() {
        return teacherVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultsubmit.teacherVerifyId
     *
     * @param teacherVerifyId the value for resultsubmit.teacherVerifyId
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public void setTeacherVerifyId(String teacherVerifyId) {
        this.teacherVerifyId = teacherVerifyId == null ? null : teacherVerifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultsubmit.adminVerifyId
     *
     * @return the value of resultsubmit.adminVerifyId
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public String getAdminVerifyId() {
        return adminVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultsubmit.adminVerifyId
     *
     * @param adminVerifyId the value for resultsubmit.adminVerifyId
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public void setAdminVerifyId(String adminVerifyId) {
        this.adminVerifyId = adminVerifyId == null ? null : adminVerifyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultsubmit.fileId
     *
     * @return the value of resultsubmit.fileId
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultsubmit.fileId
     *
     * @param fileId the value for resultsubmit.fileId
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resultsubmit.status
     *
     * @return the value of resultsubmit.status
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resultsubmit.status
     *
     * @param status the value for resultsubmit.status
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}