package cn.aethli.gttss.domain;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.userId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.classId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private String classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.batchCode
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private String batchCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gradeName
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private String gradeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studentNum
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private String studentNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.facultyId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private String facultyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.majorId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private String majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.status
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.userId
     *
     * @return the value of student.userId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.userId
     *
     * @param userId the value for student.userId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.classId
     *
     * @return the value of student.classId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.classId
     *
     * @param classId the value for student.classId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.batchCode
     *
     * @return the value of student.batchCode
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public String getBatchCode() {
        return batchCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.batchCode
     *
     * @param batchCode the value for student.batchCode
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setBatchCode(String batchCode) {
        this.batchCode = batchCode == null ? null : batchCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gradeName
     *
     * @return the value of student.gradeName
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public String getGradeName() {
        return gradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gradeName
     *
     * @param gradeName the value for student.gradeName
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setGradeName(String gradeName) {
        this.gradeName = gradeName == null ? null : gradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studentNum
     *
     * @return the value of student.studentNum
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public String getStudentNum() {
        return studentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studentNum
     *
     * @param studentNum the value for student.studentNum
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setStudentNum(String studentNum) {
        this.studentNum = studentNum == null ? null : studentNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.facultyId
     *
     * @return the value of student.facultyId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public String getFacultyId() {
        return facultyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.facultyId
     *
     * @param facultyId the value for student.facultyId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setFacultyId(String facultyId) {
        this.facultyId = facultyId == null ? null : facultyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.majorId
     *
     * @return the value of student.majorId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public String getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.majorId
     *
     * @param majorId the value for student.majorId
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId == null ? null : majorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.status
     *
     * @return the value of student.status
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.status
     *
     * @param status the value for student.status
     *
     * @mbg.generated Sat Apr 20 10:28:32 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}