package cn.aethli.gttss.domain;

import java.io.Serializable;

public class StudentBatchGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentbatchgroup.studentId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentbatchgroup.batchId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table studentbatchgroup
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentbatchgroup.studentId
     *
     * @return the value of studentbatchgroup.studentId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentbatchgroup.studentId
     *
     * @param studentId the value for studentbatchgroup.studentId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentbatchgroup.batchId
     *
     * @return the value of studentbatchgroup.batchId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentbatchgroup.batchId
     *
     * @param batchId the value for studentbatchgroup.batchId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }
}