package cn.aethli.gttss.domain;

import java.io.Serializable;
import java.util.Date;

public class SysFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfile.id
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfile.fileName
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfile.type
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfile.createBy
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfile.createDt
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfile.status
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysfile.realName
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysfile
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfile.id
     *
     * @return the value of sysfile.id
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfile.id
     *
     * @param id the value for sysfile.id
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfile.fileName
     *
     * @return the value of sysfile.fileName
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfile.fileName
     *
     * @param fileName the value for sysfile.fileName
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfile.type
     *
     * @return the value of sysfile.type
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfile.type
     *
     * @param type the value for sysfile.type
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfile.createBy
     *
     * @return the value of sysfile.createBy
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfile.createBy
     *
     * @param createBy the value for sysfile.createBy
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfile.createDt
     *
     * @return the value of sysfile.createDt
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfile.createDt
     *
     * @param createDt the value for sysfile.createDt
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfile.status
     *
     * @return the value of sysfile.status
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfile.status
     *
     * @param status the value for sysfile.status
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysfile.realName
     *
     * @return the value of sysfile.realName
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysfile.realName
     *
     * @param realName the value for sysfile.realName
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }
}