package cn.aethli.gttss.domain;

import java.io.Serializable;

public class SysUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.userId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.account
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.permission
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private Integer permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.password
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.status
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.phoneNum
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String phoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sysuser
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.userId
     *
     * @return the value of sysuser.userId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.userId
     *
     * @param userId the value for sysuser.userId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.account
     *
     * @return the value of sysuser.account
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.account
     *
     * @param account the value for sysuser.account
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.permission
     *
     * @return the value of sysuser.permission
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.permission
     *
     * @param permission the value for sysuser.permission
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.password
     *
     * @return the value of sysuser.password
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.password
     *
     * @param password the value for sysuser.password
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.status
     *
     * @return the value of sysuser.status
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.status
     *
     * @param status the value for sysuser.status
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.phoneNum
     *
     * @return the value of sysuser.phoneNum
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.phoneNum
     *
     * @param phoneNum the value for sysuser.phoneNum
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }
}