package cn.aethli.gttss.domain;

import java.io.Serializable;

public class Teacher implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.userId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.unitId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.status
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.userId
     *
     * @return the value of teacher.userId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.userId
     *
     * @param userId the value for teacher.userId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.unitId
     *
     * @return the value of teacher.unitId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.unitId
     *
     * @param unitId the value for teacher.unitId
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId == null ? null : unitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.status
     *
     * @return the value of teacher.status
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.status
     *
     * @param status the value for teacher.status
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}