package cn.aethli.gttss.domain;

import java.io.Serializable;

public class TopicWithBLOBs extends Topic implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.content
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.result
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topic.reference
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private String reference;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topic
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.content
     *
     * @return the value of topic.content
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.content
     *
     * @param content the value for topic.content
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.result
     *
     * @return the value of topic.result
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.result
     *
     * @param result the value for topic.result
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topic.reference
     *
     * @return the value of topic.reference
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public String getReference() {
        return reference;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topic.reference
     *
     * @param reference the value for topic.reference
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    public void setReference(String reference) {
        this.reference = reference == null ? null : reference.trim();
    }
}