package cn.aethli.gttss.domain;

import java.io.Serializable;
import java.util.Date;

public class TopicBook implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicbook.id
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicbook.createBy
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicbook.createDt
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    private Date createDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column topicbook.adminVerifyId
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    private String adminVerifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table topicbook
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicbook.id
     *
     * @return the value of topicbook.id
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicbook.id
     *
     * @param id the value for topicbook.id
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicbook.createBy
     *
     * @return the value of topicbook.createBy
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicbook.createBy
     *
     * @param createBy the value for topicbook.createBy
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicbook.createDt
     *
     * @return the value of topicbook.createDt
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    public Date getCreateDt() {
        return createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicbook.createDt
     *
     * @param createDt the value for topicbook.createDt
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    public void setCreateDt(Date createDt) {
        this.createDt = createDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column topicbook.adminVerifyId
     *
     * @return the value of topicbook.adminVerifyId
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    public String getAdminVerifyId() {
        return adminVerifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column topicbook.adminVerifyId
     *
     * @param adminVerifyId the value for topicbook.adminVerifyId
     *
     * @mbg.generated Thu May 02 10:23:42 CST 2019
     */
    public void setAdminVerifyId(String adminVerifyId) {
        this.adminVerifyId = adminVerifyId == null ? null : adminVerifyId.trim();
    }
}