package cn.aethli.gttss.domain;

import java.io.Serializable;

public class Unit implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.id
     *
     * @mbg.generated Mon Apr 22 09:01:09 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.name
     *
     * @mbg.generated Mon Apr 22 09:01:09 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table unit
     *
     * @mbg.generated Mon Apr 22 09:01:09 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.id
     *
     * @return the value of unit.id
     *
     * @mbg.generated Mon Apr 22 09:01:09 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.id
     *
     * @param id the value for unit.id
     *
     * @mbg.generated Mon Apr 22 09:01:09 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.name
     *
     * @return the value of unit.name
     *
     * @mbg.generated Mon Apr 22 09:01:09 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.name
     *
     * @param name the value for unit.name
     *
     * @mbg.generated Mon Apr 22 09:01:09 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}