package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.ClassName;
import cn.aethli.gttss.domain.Student;
import org.springframework.stereotype.Component;

@Component
public interface ClassNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insert(ClassName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classname
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insertSelective(ClassName record);

    ClassName selectById(ClassName className);
}