package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.DefenseDraft;

public interface DefenseDraftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defensedraft
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    int insert(DefenseDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defensedraft
     *
     * @mbg.generated Sun Apr 28 14:11:09 CST 2019
     */
    int insertSelective(DefenseDraft record);
}