package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.DefenseDraft;
import org.springframework.stereotype.Component;

@Component
public interface DefenseDraftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defensedraft
     *
     * @mbg.generated Fri May 03 01:25:04 CST 2019
     */
    int insert(DefenseDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defensedraft
     *
     * @mbg.generated Fri May 03 01:25:04 CST 2019
     */
    int insertSelective(DefenseDraft record);

    DefenseDraft selectById(DefenseDraft defenseDraft);

    void updateWithFileIdById(DefenseDraft defenseDraft);
}