package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.DefenseApply;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Controller;

@Component
public interface DefenseApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defenseapply
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    int insert(DefenseApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table defenseapply
     *
     * @mbg.generated Sat May 04 01:58:52 CST 2019
     */
    int insertSelective(DefenseApply record);
}