package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.Major;
import org.springframework.stereotype.Component;

@Component
public interface MajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table major
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insertSelective(Major record);
}