package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.MediumTermRecord;
import org.springframework.stereotype.Component;

@Component
public interface MediumTermRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mediumtermrecord
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    int insert(MediumTermRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mediumtermrecord
     *
     * @mbg.generated Thu May 02 23:55:25 CST 2019
     */
    int insertSelective(MediumTermRecord record);

    MediumTermRecord selectById(MediumTermRecord mediumTermRecord);

    void deleteById(MediumTermRecord mediumTermRecord);
}