package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.OpeningReport;
import cn.aethli.gttss.domain.OpeningReportWithBLOBs;
import org.springframework.stereotype.Component;

@Component
public interface OpeningReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openingreport
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    int insert(OpeningReportWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table openingreport
     *
     * @mbg.generated Sun Apr 21 14:15:57 CST 2019
     */
    int insertSelective(OpeningReportWithBLOBs record);

    OpeningReport selectByTopicId(OpeningReport openingReport);
}