package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.ResultSubmit;
import org.springframework.stereotype.Component;

@Component
public interface ResultSubmitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resultsubmit
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    int insert(ResultSubmit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resultsubmit
     *
     * @mbg.generated Sat May 04 17:56:19 CST 2019
     */
    int insertSelective(ResultSubmit record);

    ResultSubmit selectById(ResultSubmit resultSubmit);

    void updateWithFileIdById(ResultSubmit resultSubmit);
}