package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.StudentBatchGroup;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface StudentBatchGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentbatchgroup
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insert(StudentBatchGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table studentbatchgroup
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insertSelective(StudentBatchGroup record);

    List<StudentBatchGroup> selectByStudentId(StudentBatchGroup studentBatchGroup);
}