package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.Student;
import org.springframework.stereotype.Component;

@Component
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insertSelective(Student record);

    Student selectById(Student student);

    void updateWithNameById(Student student);
}