package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.DefenseDraft;
import cn.aethli.gttss.domain.SysFile;
import org.springframework.stereotype.Component;

@Component
public interface SysFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysfile
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    int insert(SysFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysfile
     *
     * @mbg.generated Fri May 03 01:54:06 CST 2019
     */
    int insertSelective(SysFile record);

    void updateWithStatusById(SysFile sysFile);

    SysFile selectById(SysFile sysFile);
}