package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.SysUser;
import org.springframework.stereotype.Component;

@Component
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insertSelective(SysUser record);

    SysUser selectByAccount(SysUser sysUser);

    SysUser selectById(SysUser sysUser);
}