package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.Teacher;
import org.springframework.stereotype.Component;

@Component
public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insertSelective(Teacher record);

    Teacher selectById(Teacher teacher);
}