package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.TopicStudentGroup;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Component
public interface TopicStudentGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicstudentgroup
     *
     * @mbg.generated Sat Apr 20 14:54:46 CST 2019
     */
    int insert(TopicStudentGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topicstudentgroup
     *
     * @mbg.generated Sat Apr 20 14:54:46 CST 2019
     */
    int insertSelective(TopicStudentGroup record);

    int selectCountByTopicId_BatchId(Map<String, Object> m);

    List<TopicStudentGroup> selectByTopicId(Map<String, Object> queryMap);

    TopicStudentGroup selectByTopicId_studentId(TopicStudentGroup topicStudentGroup);

    void deleteByTopicId_studentId(TopicStudentGroup topicStudentGroup);

    TopicStudentGroup selectByStudentId(TopicStudentGroup topicStudentGroup);
}