package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.TopicType;
import org.springframework.stereotype.Component;

@Component
public interface TopicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topictype
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insert(TopicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table topictype
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insertSelective(TopicType record);
}