package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.Teacher;
import cn.aethli.gttss.domain.Unit;
import org.springframework.stereotype.Component;

@Component
public interface UnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Mon Apr 22 09:01:09 CST 2019
     */
    int insert(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbg.generated Mon Apr 22 09:01:09 CST 2019
     */
    int insertSelective(Unit record);

    Unit selectById(Unit unit);
}