package cn.aethli.gttss.dao;

import cn.aethli.gttss.domain.Verify;
import org.springframework.stereotype.Component;

@Component
public interface VerifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insert(Verify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table verify
     *
     * @mbg.generated Sat Apr 20 09:20:33 CST 2019
     */
    int insertSelective(Verify record);

    Verify selectById(Verify verify);
}